### ISSUE TITLE
stuck at the Sunday church confession

### ISSUE THREAD

**Issue by raywen1897** [fapforce5/HatMP#89]
![Screenshot 2023-12-02 013405](https://github.com/fapforce5/HatMP/assets/152619860/091e45c1-c8b3-40f6-8524-290bfa6bfa54)

**Comment by fapforce5** [comment]
Thank you.  That is a bug I need to look into. The only way to get out
Press the f12 key
Click the console tab and enter
char.room(0);
That should take you to the map

**Comment by fapforce5** [comment]
Fixed and pushed
